[tool.poetry]
name = "my-gl-example"
version = "0.1.0"
description = "An example application for greenlight that uses the gl-client library"
authors = []
license = "MIT"

[tool.poetry.dependencies]
gl-client = {path = "../../libs/gl-client-py"}
pytest = "^7.1.2"
python = ">=3.7,<4"
