on:
  push:
    branches:
      - master
    tags:
      - 'gl-sdk-*'
  pull_request: {}

name: Kotlin library

jobs:

  build:
    runs-on: macos-26
    steps:
      - name: "Show default version of NDK"
        run: echo $ANDROID_NDK_ROOT

      - name: "Check out PR branch"
        uses: actions/checkout@v4

      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          targets: x86_64-linux-android, aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: "Install NDK"
        run: |
          cargo install cargo-ndk --version 3.5.4

      - name: "Build Kotlin Multiplatform bindings"
        run: |
          /usr/local/bin/task build:android

      - name: "Build Android library"
        working-directory: libs/gl-sdk-android
        run: |
          ./gradlew :lib:assemble --console=plain

      - name: "Puiblish to Maven"
        working-directory: libs/gl-sdk-android
        run: |
          ./gradlew :lib:publishToMavenLocal

      - name: Temporarily save artifact
        uses: actions/upload-artifact@v4
        with:
          name: glsdk-artifact
          path: libs/gl-sdk-android/lib/build/outputs/
          retention-days: 14
